-- Supabase SQL Editor'de bir kez çalıştır.
create table if not exists public.menu (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Çorbalar',
  price numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.menu enable row level security;

-- Örnek ürünleri yalnızca tablo boşsa ekle.
insert into public.menu (name, category, price)
select seed.name, seed.category, seed.price
from (values
  ('Mercimek Çorbası', 'Çorbalar', 150),
  ('Ezogelin Çorbası', 'Çorbalar', 200),
  ('Kelle Paça Çorbası', 'Çorbalar', 270)
) as seed(name, category, price)
where not exists (select 1 from public.menu);
